### ISSUE TITLE
core::alloc::Alloc no longer exists in rust nightly. It is replaced by AllocRef.

### ISSUE THREAD

**Issue by yima77** [alexcrichton/dlmalloc-rs#10]
Now, dlmalloc build fails with:

error[E0432]: unresolved import `core::alloc::Alloc`
  --> /home/xyz/.cargo/registry/src/github.com-1ecc6299db9ec823/dlmalloc-0.1.3/src/lib.rs:21:19
   |
21 | use core::alloc::{Alloc, Layout, AllocErr};
   |                   ^^^^^ no `Alloc` in `alloc`

**Comment by TimDiekmann** [comment]
The `AllocRef` trait is currently highly unstable and in the next weeks you can expect quite a few changes. I will probably make a PR when [#38](https://github.com/rust-lang/wg-allocators/issues/38), [#41](https://github.com/rust-lang/wg-allocators/issues/41), and [#42](https://github.com/rust-lang/wg-allocators/issues/42) at [the allocator wg](https://github.com/rust-lang/wg-allocators) are merged.

**Comment by TimDiekmann** [comment]
Depending on how fast we move forward, this will be fixed with https://github.com/rust-lang/wg-allocators/issues/21 (`impl<T: GlobalAlloc> AllocRef for T`).
