### ISSUE TITLE
Allow GlobalDlmalloc to be backed by a custom Allocator instance

### ISSUE THREAD

**Issue by bjorn3** [alexcrichton/dlmalloc-rs#38]
This would allow using it in `#![no_std]` contexts.

**Comment by bjorn3** [comment]
It looks like that would also require a way to specify the global lock.

**Comment by yavko** [comment]
Why close the issue

**Comment by bjorn3** [comment]
I initially opened this issue with the idea that this would be enough for no_std usage, but given that there are much more changes necessary, using GlobalDlmalloc in no_std use cases is probably not worth it. Instead writing your own GlobalAllocator instance based on Dlmalloc would be much easier.

**Comment by yavko** [comment]
> I initially opened this issue with the idea that this would be enough for no_std usage, but given that there are much more changes necessary, using GlobalDlmalloc in no_std use cases is probably not worth it. Instead writing your own GlobalAllocator instance based on Dlmalloc would be much easier.

I see
