### ISSUE TITLE
dlmalloc is larger on wasip1 target than unknown-unknown

### ISSUE THREAD

**Issue by XinyuZeng** [alexcrichton/dlmalloc-rs#45]
Hi, I am just curious about the reason behind this behavior: https://users.rust-lang.org/t/code-size-of-wasip1-larger-than-unknown-unknown/122789

For wasi, is that we should include our own allocator?

**Comment by alexcrichton** [comment]
I believe what's happening there is that the Rust `wasm32-wasip1` target is using wasi-libc by default for malloc, not this crate. You can still use this crate though with `#[global_allocator]` instead.
